name: build-and-release

on:
    push:
        branches: [master]
        tags:
            - "v*"
defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-15-intel, ubuntu-24.04, windows-2022]
        steps:
            - name: checkout repo
              uses: actions/checkout@v2

            - name: Install pandoc
              uses: pandoc/actions/setup@v1

            - name: Install git sdk
              if: runner.os == 'Windows'
              uses: git-for-windows/setup-git-for-windows-sdk@v1
              with:
                  flavor: full

            - name: Install dependencies on Linux
              if: runner.os == 'Linux'
              run: |
                sudo apt-get install -y libxcursor-dev libxft-dev libxss-dev

            - name: Install macOS dependencies
              if: runner.os == 'macOS'
              run: |
                   brew install swig

            - name: build application
              run: ./make-ci.sh ${{ matrix.os }}

            - name: upload result
              uses: actions/upload-artifact@v4
              with:
                  name: build-${{ matrix.os }}
                  path: dist/*.tar.bz2

    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              id: download
              with:
                  path: ~/downloads

            - name: Create tarball dir
              run: mkdir tarballs

            - name: Collect all artifacts
              run: find ${{steps.download.outputs.download-path}} -type f -exec mv {} tarballs \;

            - name: Display structure of downloaded files
              run: ls -R

            - name: Release nightly
              if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
              uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: |
                    tarballs/*.tar.bz2

            - name: Release tagged version
              if: ${{ startsWith(github.ref, 'refs/tags/v') }}
              uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: |
                    tarballs/*.tar.bz2
